version: '3.3'
services:
  app:
    build:
      context: app
    volumes:
      - ../src:/var/www/app
      - ./app/cmd.sh:/var/www/app/cmd.sh
    expose:
      - 9000
    ports:
      - 8000:8000
      - 7000:7000
      - 6000:6000
      - 5000:5000
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../src:/var/www/app
